services:
  bb:
    # uncomment if you want to build the image yourself!
    # build: .
    image: ghcr.io/astrabun/yabb:main
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./config.yml:/app/config.yml:ro
      - ./data:/app/data
    environment:
      - CONFIG_PATH=/app/config.yml
      - DATA_DIR=/app/data
